### ISSUE TITLE
Para cuándo es necesario esto??

### ISSUE THREAD

**Issue by lmagarin** [javiloji/ReEntregaMastermindJavaScript#4]
https://github.com/javiloji/ReEntregaMastermindJavaScript/blob/f3ad2c72f85e2b6536c73cdcbb427328f9421591/js/Mastermind.js#L59

**Comment by javiloji** [comment]
Es necesario primero para ordenar el array y luego para ponerlo en orden inverso ya que lo ordena de menor a mayor y yo quiero mostrarlo de mayor a menor

**Comment by lmagarin** [comment]
👍 
Podrías haberle puesto a cada numérico un nombre. 
Así haces tu código más legible
